# Generated by Django 5.2.11 on 2026-04-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_moviecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='comment',
            new_name='like',
        ),
    ]
