# Generated by Django 5.2.11 on 2026-04-13 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_comment_moviecomment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='like',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
